/**
 * Self-host the webfonts. `npm run fonts`
 *
 * Closes the TODO in index.html: three families from fonts.googleapis.com cost
 * a DNS + TLS handshake to a third party on the critical path, and the font
 * files themselves are a second hop to fonts.gstatic.com. Both block first text
 * paint, which is exactly the LCP the perf budget cares about.
 *
 * Google already ships these split by writing system with `unicode-range`, so
 * keeping only the `latin` block IS the subsetting step — no fonttools needed.
 * Re-run this if a family or weight range changes; it rewrites fonts.css.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUT_DIR = path.join(ROOT, 'public/fonts');
const CSS_OUT = path.join(ROOT, 'src/styles/fonts.css');

// Same request the browser makes — the UA decides whether we get woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
const SRC =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800&family=Inter:wght@300..700&family=JetBrains+Mono:wght@400;500&display=swap';

// Only the writing systems the site actually renders.
const KEEP = new Set(['latin']);

fs.mkdirSync(OUT_DIR, { recursive: true });

const css = await (await fetch(SRC, { headers: { 'User-Agent': UA } })).text();

// Blocks arrive as: /* subset */\n@font-face { ... }
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];
if (!blocks.length) throw new Error('Could not parse Google Fonts CSS — did the format change?');

const out = [];
const seen = new Set();
let bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim();
  if (!url || !family) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight.replace(/\s+/g, '-')}-${subset}.woff2`;
  if (!seen.has(file)) {
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, file), buf);
    bytes += buf.length;
    seen.add(file);
    console.log(`${file.padEnd(52)} ${(buf.length / 1024).toFixed(1)} KB`);
  }

  out.push(block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${file}')`).trim());
}

fs.writeFileSync(
  CSS_OUT,
  `/* GENERATED by scripts/fonts.mjs — do not edit by hand. Run \`npm run fonts\`.
   Self-hosted so first text paint doesn't wait on fonts.googleapis.com +
   fonts.gstatic.com. Latin subset only; see the script for why. */\n\n${out.join('\n\n')}\n`
);

console.log(`\n${seen.size} files, ${(bytes / 1024).toFixed(1)} KB total → public/fonts/`);
console.log(`wrote ${path.relative(ROOT, CSS_OUT)}`);
